### ISSUE TITLE
Players can loose inventory

### ISSUE THREAD

**Issue by dwi** [Minebench/SyncInv#3]
- Two server, **A** and **B**, both set to synchronize inventories
- Player plays on server **A** and never joined server **B** (so the playerdata is only on A)
- Server **A** goes down. Player decides to join server **B** and he joins with fresh new empty inventory.
- Server **A** goes up again, player joins server **A** and  SyncInv changes his A-inventory with empty one from server **B**

Can this somehow be prevented? Maybe force OpenInv to create the playerdata?

**Comment by Phoenix616** [comment]
Yeah, it was first designed with syncing inventories on server switches in mind and the permanent storage part was added later. I also took a look at creating player data when I added OpenInv but it didn't seem to have that ability so I put that feature on halt as it would've required my to add version depended NMS code to the plugin - the sole reason I relied on OpenInv in the first place.

The solution that I use on my server is to only let players connect to their logout server - and if it's offline they can't connect to the whole cluster. (This obviously isn't ideal) A better way could be to create a separate server listening on the same pub-sub redis channel and store all inventories in a database but that would kinda defeat the original purpose and make it centralised again so the playerdata creation might be a better solution after all.

**Comment by Phoenix616** [comment]
Could you please test if [build 27](https://ci.minebench.de/job/SyncInv/27/) does what you imagine? I seem to have solved the issue (the way is a bit hacky though but it should work pretty reliably)

**Comment by dwi** [comment]
Will try, thanks!

**Comment by dwi** [comment]
Few observations, will post them there as the issues occure:

Getting this error on the start when there are no maps on the server or the world/data/ folder is empty (for newly created server)

> [INFO] Enabling OpenInv v3.3.0
>[INFO] Enabling SyncInv v0.2-SNAPSHOT (build #27)
[INFO] Debug: Sending HELLO to group:survival containing 0 objects.
[INFO] Debug: Received HELLO from novus targeted at space2
[ERROR] Error occurred while enabling SyncInv v0.2-SNAPSHOT (build #27) (Is it up to date?)
java.lang.NullPointerException: null
        at de.minebench.syncinv.SyncInv.onEnable(SyncInv.java:162) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[patched_1.12.2.jar:git-Paper-1414]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316) [patched_1.12.2.jar:git-Paper-1414]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [patched_1.12.2.jar:git-Paper-1414]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:395) [patched_1.12.2.jar:git-Paper-1414]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:344) [patched_1.12.2.jar:git-Paper-1414]
        at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:442) [patched_1.12.2.jar:git-Paper-1414]
        at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:403) [patched_1.12.2.jar:git-Paper-1414]
        at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:341) [patched_1.12.2.jar:git-Paper-1414]
        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:293) [patched_1.12.2.jar:git-Paper-1414]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616) [patched_1.12.2.jar:git-Paper-1414]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]
[INFO] Disabling SyncInv v0.2-SNAPSHOT (build #27)
[INFO] Debug: Sending sync BYE to group:survival containing 0 objects.

**Comment by Phoenix616** [comment]
Should be fixed with 476090a7cef17886b690fcec0156e724c03a1cad.
